package com.coursemanagement.CourseManagement.Entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.coursemanagement.CourseManagement.Util.LocalDateTimeConverter;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Discussion")
public class Discussion {

    @DynamoDBHashKey(attributeName = "discussionId")  // Primary Key
    @DynamoDBAutoGeneratedKey
    private String discussionId;

    @DynamoDBAttribute(attributeName = "question")
    private String question;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "courseIdIndex", attributeName = "courseId")//GSI
    private String courseId;

    @DynamoDBAttribute(attributeName = "date")
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    private LocalDateTime date;
}
