package com.coursemanagement.CourseManagement.Entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.coursemanagement.CourseManagement.Static.Role;
import com.coursemanagement.CourseManagement.Util.RoleConverter;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "User")
public class User {

    @DynamoDBHashKey(attributeName = "userId")
    @DynamoDBAutoGeneratedKey
    private String userId; //partition key

    @DynamoDBAttribute(attributeName = "name")
    private String name;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "emailIndex", attributeName = "email")
    private String email; //GSI

    @DynamoDBAttribute(attributeName = "password")
    private String password;


    @DynamoDBAttribute (attributeName = "role")
    @DynamoDBTypeConverted(converter = RoleConverter.class)
    private Role role; //GSI


}
