package com.SocialMedia.SocialMedia.Entities;

import com.SocialMedia.SocialMedia.Util.LocalDateTimeConverter;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Comment")
public class Comment {

    @DynamoDBRangeKey(attributeName = "commentId")
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "commentIdIndex", attributeName = "commentId")
    @DynamoDBAutoGeneratedKey
    private String commentId;

    @DynamoDBAttribute(attributeName = "commentorId")
    private String commentorId;

    @DynamoDBAttribute(attributeName = "commentText")
    private String commentText;

    @DynamoDBHashKey(attributeName = "postId")
    private String postId;

    @DynamoDBAttribute(attributeName = "commentDateTime")
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    private LocalDateTime commentDateTime;
}
