package com.SocialMedia.SocialMedia.Entities;

import com.SocialMedia.SocialMedia.Util.LocalDateTimeConverter;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Post")
public class Post {

    @DynamoDBHashKey(attributeName = "postId") //partition key  //GSI sortKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "userPostIndex",attributeName = "postId")
    private String postId;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "userPostIndex", attributeName = "userName") //gsi partition key
    private String userName;

    @DynamoDBAttribute(attributeName = "postPath")
    private String postPath;

    @DynamoDBAttribute(attributeName = "postName")
    private String postName;

    @DynamoDBAttribute(attributeName = "postCaption")
    private String postCaption;

    @DynamoDBAttribute(attributeName = "postDate")
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    private LocalDateTime postDate;

    @DynamoDBAttribute(attributeName = "likes")
    private Integer likes =0;

    @DynamoDBAttribute(attributeName = "comments")
    private Integer comments=0;

}
