package com.springboot.dynamoDB.ExpenseTracker.Entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.springboot.dynamoDB.ExpenseTracker.Util.LocalDateTimeConverter;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.format.annotation.DateTimeFormat;

import java.time.LocalDateTime;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Transaction")
public class Transaction {

    @DynamoDBHashKey(attributeName = "transactionId") //partition key
    @DynamoDBAutoGeneratedKey
    private String transactionId;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "userId-date-index") //GSI partition key
    private String userId;

    @DynamoDBAttribute(attributeName = "amount")
    private double amount;

    @DynamoDBAttribute(attributeName = "type")
    private String type;

    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class) //GSI sort Key
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "userId-date-index")
    private LocalDateTime date;

    @DynamoDBAttribute(attributeName = "description")
    private String description;

    @DynamoDBAttribute(attributeName = "category")
    private String category;

}
