package com.coursemanagement.CourseManagement.Entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.coursemanagement.CourseManagement.Util.LocalDateTimeConverter;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@DynamoDBTable(tableName = "Answer")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Answer {

    @DynamoDBHashKey(attributeName = "answerId") //partition key
    @DynamoDBAutoGeneratedKey
    private String answerId;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "discussionIdTimeIndex", attributeName = "discussionId") //GSI
    private String discussionId;

    @DynamoDBAttribute(attributeName = "responderId")
    private String responderId;

    @DynamoDBAttribute(attributeName = "answerText")
    private String answerText;

    @DynamoDBIndexRangeKey(attributeName = "answeredAt")
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    private LocalDateTime answeredAt;
}
