package com.coursemanagement.CourseManagement.Entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "CourseId")
public class Courses {

    @DynamoDBAttribute(attributeName = "courseId")
    @DynamoDBAutoGeneratedKey
    private String courseId;

    @DynamoDBAttribute(attributeName = "title")
    private String title;

    @DynamoDBHashKey(attributeName = "instructorId")
    private String instructorId; //partiton key

    @DynamoDBAttribute(attributeName = "studentCount")
    private int studentCount;

}
