package com.coursemanagement.CourseManagement.Entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Course")
public class Course {

    @DynamoDBHashKey(attributeName = "courseId")
    @DynamoDBAutoGeneratedKey  //partition key
    private String courseId;

    @DynamoDBAttribute(attributeName = "title")
    private String title;

    @DynamoDBIndexHashKey( globalSecondaryIndexName = "instructorIdIndex", attributeName = "instructorId") //sortKey
    private String instructorId;


}
