package com.springboot.dynamoDB.ExpenseTracker.Entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "User")
public class User {

    @DynamoDBHashKey(attributeName = "userId")
    @DynamoDBAutoGeneratedKey
    private String id;  // Partition Key

    @DynamoDBAttribute(attributeName = "name")
    @NotBlank(message = "Name cannot be blank")
    private String name;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "email") //GSI
    @Email(message = "Invalid email format")
    private String email;

    @DynamoDBAttribute(attributeName = "password")
    @Size(min= 8, max= 16, message = "Password must be 8 to 16 characters long")
    private String password;

    @DynamoDBAttribute(attributeName = "balance")
    private double balance;


}
